name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Build app
        run: npm run build

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t oakline-bank:${{ github.sha }} .
          docker tag oakline-bank:${{ github.sha }} your-dockerhub/oakline-bank:latest
          docker push your-dockerhub/oakline-bank:latest

      - name: Deploy to Kubernetes
        uses: azure/k8s-deploy@v4
        with:
          manifests: |
            infra/kubernetes/deployment-app.yaml
            infra/kubernetes/service-app.yaml
            infra/kubernetes/ingress.yaml
          images: |
            your-dockerhub/oakline-bank:latest
          namespace: oakline-bank
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
