
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: placeholder-hpa
  namespace: placeholder-namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: placeholder-app
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
